#!/usr/bin/env bash
# 
# Bootstrap script for setting up a new OSX machine
# 
# This should be idempotent so it can be run multiple times.
#
# Some apps don't have a cask and so still need to be installed by hand. These
# include:
#
# - Xcode
#
# Reading:
#
# - http://lapwinglabs.com/blog/hacker-guide-to-setting-up-your-mac
# - https://gist.github.com/MatthewMueller/e22d9840f9ea2fee4716
# - https://news.ycombinator.com/item?id=8402079
# - http://notes.jerzygangi.com/the-best-pgp-tutorial-for-mac-os-x-ever/

echo "Starting bootstrapping"

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

echo "Installing Apple Command Line Tools"
xcode-select --install

# Check for Homebrew, install if we don't have it
if test ! $(which brew); then
    echo "Installing homebrew..."
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Update homebrew recipes
brew update

PACKAGES=(
    node
    python
    postgresql
    wget
    zsh
)

echo "Installing packages..."
brew install ${PACKAGES[@]}

echo "Installing cask..."
brew tap caskroom/cask

CASKS=(
    1password
    battle-net
    deluge
    dropbox
    google-chrome
    iterm2
    league-of-legends
    keka
    omnifocus
    slack
    spectacle
    spotify
    steam
    vlc
)

echo "Installing cask apps..."
brew cask install ${CASKS[@]}

echo "Cleaning up..."
brew cleanup
brew cask cleanup

echo "Installing fonts..."
brew tap caskroom/fonts
FONTS=(
    font-menlo-for-powerline
)
brew cask install ${FONTS[@]}

echo "Installing oh my zsh"
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

echo "Post-install set up"

# Make zsh be the default shell
sudo sh -c 'echo "$(which zsh)" >> /etc/shells'
chsh -s $(which zsh)

# Actually install Battle.net
if [ ! -d /Applications/Battle.net.app ]; then
    open /usr/local/Caskroom/battle-net/latest/Battle.net-Setup.app
else
    echo "Battle.net already installed"
fi

# Use .zshrc from dotfiles repo
echo "Using dotfiles repo .zshrc"
cp .zshrc ~/.zshrc

# Set up git config
echo "Setting up git config"
git config --global user.name "Michael Poon"
git config --global user.email michael.l.poon@gmail.com

echo "******************"
echo "TODO"
echo "- Change iterm preferences to use Solarized Dark"
echo "- Change iterm preferences to use Menlo for Powerline font"

echo "Bootstrapping complete"
